# Generated by Django 4.1.1 on 2022-10-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=100)),
                ('car_number', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.DateTimeField(null=True)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('owner', 'owner')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WashCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Washer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='washer',
            constraint=models.UniqueConstraint(fields=('name', 'phone'), name='name and phone error'),
        ),
        migrations.AddField(
            model_name='user',
            name='washcompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.washcompany'),
        ),
        migrations.AddField(
            model_name='service',
            name='washcompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.washcompany'),
        ),
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.car'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.service'),
        ),
        migrations.AddField(
            model_name='order',
            name='washer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.washer'),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.UniqueConstraint(fields=('car_model', 'owner_name', 'owner_phone'), name='car_model, car_owner and car_phone error'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('role', 'washcompany'), name='role and washcompany error'),
        ),
    ]
